apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - placements.100xdevs.com
      secretName: job-board-tls
    - hosts:
      - projects.100xdevs.com
      secretName: dailycode-tls
    - hosts:
      - app.100xdevs.com
      secretName: cms-tls
  rules:
    - host: placements.100xdevs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: job-board
                port:
                  number: 80
    - host: projects.100xdevs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dailycode
                port:
                  number: 80
    - host: app.100xdevs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cms
                port:
                  number: 80
