---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: webinar-api-secrets
  namespace: default
spec:
  encryptedData:
    .env: AgB0UXNWGz7b8P77t4PP+RxcIa2n7zArHtSxeM8dS9YLtyOXjwkYwxLItSt2rs6okJDLevFo/GLz4nJY3xZrw3WzA4iVe92j/vMz9wJXGoshQCv16z6QT4riU+s4RYJ1XfHiS1RVdMtfm5YHGjFpF6AE/j5HZlOBYWSs+WikgwhaqKS6RMAuPNu9EAYxlBhPxA0ne2P2rrtR0CYvPVmWLfOY/ai1NJwTDIFxIrhxQETzPNpJcyn99AbyJ9pRoU3u8wPmcBr57mPO9L5XJA1hw5C0SMdkgxMvC5ro3afN9rixw7Eqmg34NZsBV+W+nYdZcworeEdlcn3D0bzotfEhp3+TNrtkmRZmuMNRbvHxYW3xQbLFcn7kpUcNR6DRs6dyrzOGKK550WCBQnQPfp/6LIcdQgODTp4HOIRM7vuSBrGa+4YpshJpFcECihnUmEYtm0teKzw/v7B0HfFhTT0gl3bXAQvHHhy+KssUWl30xVvOK22Fkm6ptuIhjYoDIlfEzMBSsjSZm6VttjwCkWAcGBgaRMyy4XfiyJH25i2LAHHlxaXdwoDgBs4sGKjXpojXvK5T0o/ibTgMigaXfnoTKCOX/lgl4mb2H35cQcMmRpcN7I1t3O+2fbUzZt05sWSA7LcJcTk/yzbe1+qkSWWGbS/Sgo9KzsXSn8Ty97t9KMKAMPq1l/49ztcKT7IE6sa+eIKHRpl/CKKtfMc/3atLnPuB3Dad4cmcItjlwGtoq7mc5lpWxwUNdn6yHcME/J4ktqvfWcawphJl1dAe60UtHxOfx3zCHJLPqZtRVCOOYj72QXFdn7sCKvChaML8fHvp3vMqnKd+H4nawyyiOZOW/yH/fJP2RowXd9KzHZsunfFvPLxByrWUjJF3XJmRkm3H3JJJcfnAVQS4SOe2dNme60K1UosWorccmeaxawkQoyA+FbvjQ34eHuP4cyrjtDZ9Bh9m4VVjNhx6+xKV++aEbmlKiksvbcBftYBhOLuoygfWJQGlU72aLZ5AUR5YUAPJ5P5rrK1yKJonMH1BWu1R7dC4x2MgjLZH84xBPDLp0zwai0kMCPZxOEk539dyuRM3+WfWAHYfEYnItoxOnGp/qa1nKSVNnUmwgB1rTNrDpD3R+hNSZetNqYUFYXyUgQRo7i2r/TFSWaPnDahVfxeDbr6dEuuOGv1xI76B6cVQhCd2NcEjS3KHiLIXGQGeraN3SAQedkw9ufUgtpB36arYfp5QUa7j3k+4Lk2X/5xPBUhKhdIkA4UbmqXC/my8/f6HKT25psZY4NdHCOAEXBwI/2yPjyGvXj2GaLu9S8AloIixTvY06DJOLhsz2holcZy9OqfryU6hz1SOe5Mp7BeWxuSD+XTWpaVsQeVgCTBw1GVNn7WBpaFuC1qv8WygDqKeyBmDDvISbt1mU8yVuLpon+l89HKS3jUcubQBv49xkj55tn+WlnQ8D+b/aT9i2Q6wxNUqb5PfBXQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: webinar-api-secrets
      namespace: default
    type: Opaque
