apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-ws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webinar-ws
  template:
    metadata:
      labels:
        app: webinar-ws
    spec:
      containers:
        - name: webinar-ws
          image: 100xdevs/webinar-ws:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-ws
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webinar-ws
