apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cms-staging-cert
  namespace: default
spec:
  secretName: cms-staging-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: staging.app.100xdevs.com
  dnsNames:
  - staging.app.100xdevs.com
