apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-board-staging
  labels:
    app: job-board-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-board-staging
  template:
    metadata:
      labels:
        app: job-board-staging
    spec:
      containers:
        - name: job-board-staging
          image: 100xdevs/job-board-staging:8f382d61a2c6111b8806701b5455b304615ed1e6
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: secret
              mountPath: /usr/src/app/.env
              subPath: .env
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: secret
          secret:
            secretName: job-board-staging-secret
            items:
              - key: .env
                path: .env
