---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: job-board-staging-secret
spec:
  encryptedData:
    .env: AgBTJ+Af8GLudHqhVCPYDhEfqxbJOGhcOCoWnzJO4mgztzkISR26n3guhEPwABjtec2suWWAwCnAdO7NxzIa1SXv17RxdT0Wegyl2T6kkc3ilWAOE2Y0O4eIiojBebhVu5rH/HnYncBYX9GlYHaCiLVhGNBx/vKMp1QiII/AUFyXnHoFSDko8meFL4xvHiiGRYDyOm3dVkg9pn3qsqepBEP5kabUqIm8zkrsDKQIkHWwZlvnYE1sTSwkNldNZgtlgYVNwdvw4SbIMFvSoZwxZU8oSomLNiZX4M7MTv1NVrFGJoeX55jBaoDe9pvIJIEWvXyf39yfzK9h0yePOCOc41KPmzJtyNBjOty5DQnp8CwZOTjLVlqktFZI9HFWfqOAR8ZtikEN3QuBXxMAJ9rPllbcWN4pVSFFH2jYl2q4k30/6O1eUJO8fwZ7ztepMZ3I37F7Dt4VoYbu/5w+tIIAgYtudR18e8+Tqmx1cpiUndT7L/fTYBHnIwhZjN/O8QgCdWdGKyOz1LGJCvqOqOPfdbe6AC7ZmLDu2BMBl341PRei1PtDE/ob0fAYodleKr8/bhSV96PCUoe5IMzct42a4evuokvHD/v5tn9q4Ix2M50DvvzSvlvJe6FmJWkMT4sXj/AUrhuZuBFZquuWoF/Rw8CyHcCqdLF0iuzEn0o0t3JZrBppXAdZHPSfvqiq+ruVNjO6Ad0wD3StCihX0PV61xhW9kP4+6deR/hBIHr/wkQ3Oc83OPuJm6aN/xKrTmKTiK9eZpXK9CvveVJLaI8jypCPl58NtQ16fHG8wAS6JE/OppD+dRerzdy6hHmSnBQUswQ0aCRs34XuJcU0bnV1aE2oSD5O/+TSy03NtyPXn1KWIELuhJvKwdbAsFECD5Pjuus3K5TueVlqDy0bUG8JIWP2u+TqU6JsZ/TpQx00/wwixP00xRgJX0nh/XteIWTmXDVmQojaN5xzkzx1Q2JtMRbDvgwaIumfCo10gJj7UDU1mrihwd3suzbzkQ3Ewussn1uFL2NOUtDGdYyvJprb+Dk5go8tylO/2HLJCIsV5N0E1L+Fq3hdHeg46nCYfdjtZeTIMChIqNnXKbIr1gFbQx/LgnoR+KXbKkZQBLfRSubZgrbhrTvcF7gc3uD3aL6sgcC2AQIsTgXNbkE9y1Ec6b/V1wAkYRrCiAm2xQ6kXWmTRjZbjPzniIKxQTvIBhS9U7HBOfXg87ycSRuWfPasd+zLQ1Kem0VdzqVp71G6mrMt5cCMWtLicspWIi17jGSl/Lo7epBD0MgvZgzulXmaUu70RwJCkm5PzpY9e6zni8dartc4E0mxVIJOf0T5mO0Jnc9/AoH1jBb9ffOXG6CMughL4Bi1HCOdn9qEegZkpSVIoLA0Kr45gMl1orfZks/cviNFqHg8jnrl2XYwz1c+mFKYT/an3cpHSjFBpYPX71XwHQvKNp2hnp9lZJuS5bowFb3erTa+zB/ll1BJz1b/mN5KoyEeagqpewSS8N3BJDkkl6kLKE/T6yWqRPLtZHIWq+/KioRTidWXXVhCS5MObKl4LF7oqB83Rz7yjKvwj1syM6MQ3+sA0D3Coxr3Kg3NxA2uaz3sQfIgBzWeIHjp6lQ71CtwYzsAKA0nj3xTAxE+Yw0Gm9+DbDYl0g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: job-board-staging-secret
    type: Opaque
