---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: job-board-staging-secret
spec:
  encryptedData:
    .env: AgARu2qEY8CemRYGy3Jl+O7IShL5TIc0RUVcuUanDFOffV97b4Dv9Xan+OXWauX7bPYIefLpKPHRXCkBoAUaaX7KO+rmrAtt+p8n82im0cn+WpLB7YmJjzfjHtm6/x4nNVOC6+FH1mbtRSPf7DrPVJ5RgpjwcIFuCgtwExFXjXCJXhLq80BVBKwcg/spjLi6BhiPwClNvk0YwroA3AETgSjTxVjY/zorB1WREp/QBtIBKB+GZ2cwy0ztbD3aZysCVVfeQrAWe7WNgHf6YhznnIeJtETB8CG4FNFC7sn3vgQ5J00lO8ecs5vdqq5ISlgSSf7y6TYVNJ3addyLUbAY9RFTpD/b+Q0wFGlfIDtTMNzO+tgALWEDF2s4hD+YBxhT26LOZ90d/hb/QlaxJcaHHVPnMgIYTq11pVr804T4jX8mbrulAnqhgux3AS1NO3bbEZboxS+YoVEUPnnoU20mhpRQfR531L4zTpMsRZJ4YaA0J56He0L9eJRiWUmoijJpHlYPY2c+Shxe0X7VPBlIcNqxmRDDhuNBk9lF4K1NXQjHYiz8Pd+7fwSLu60Fmx/HnKK52tzGJrOBP0JxcrEBSd0Z93cW+TThtpOfGwcmswZBGVugYSsMhgy2kXQDYqDnJ8OCfRrsj2w5SLgfDY5vai1tgNTg+YSpGfUYV0abyUXDYg2jDi9vVfSaB5hSEOaYw9QgjXTasbI9SfA5nE1YcLVKw9HBZpLlB9+zW69Ft2ZHtmiGRf3H+u3mqVRPxF/5n/iRsOdy3BLF7xjn72X+/IqywskTlMtUO8q0PvKrjCtKAoBTSG2JCOchCwKeoQiPKPG+zvu9KamL2FCX4hjKkrsXU1//v+c7M51O34y1GEFFCMZoHJ2LKxIEpnA4yyoCe6tJZVC14vLnmZ/cofWFnt7uLURKM5JzH5IwJekQy7tVB0Y4hg58erDmAY1++BCtgo4FzZrJkszz4oZx1GtENQIOlg57Koh8lL980hb+ULfcEoIc4dfP6pzzAE5RPM0cqA7WQ0Wgo9biEiHLo7Z2fGpwKXX8SZ44qGJNUH3ic8NA9tJrVqrucoc4QoxqR8+3N8AoOG5FSvXOOYsSHGeOV4VfIb7f7N7od2DsmJmKZ3k7sOGNhmXffWERQJNYam1aqlmR6fAfBHujfOP0TOLYN0/gUrGIDOYpfU2DKTsf2FUYa10sloYARJtFYmfncAZpY+95qsPSTvxmJgQld3GBtdopbELP0f1Lxy1db9ifcRmWMnvFvGCEV1PKhIUKSRM/3lJ6btWa7AOiW8dePG/h3OkyxxTXGnSr212K5JFZHbCclWQPKKSEUxg/2jPizm5ZGmASk1lkOUVyrsEJlyKEZB1/pCDDN6jNfaP3T71h6LfxNlpq9kYrDARq1Yz0f3HcprtqIHqq1nFPA1vh9bVMJaFvQ2/qWZjtJdAjtE3hUMMGcibpQKKAqe0CvE5aCH0gFICBeyOO+paj3zgjQF//GLcPcgU8h+LmFkWFqUNud4Y6NBLvJdnazGbPTfGaUivTsE1wwwrSVWx34E5UrEw65ncJ7MYl4NWe0E5omoMBMi4Sirb7PKdTTWRBYZCBG+gBZX6ECvSjJxiNTVYh8OAikXO56aPws9VaiEWmCOqyqvZWE5mOBx1k320=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: job-board-staging-secret
    type: Opaque
