apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-backend-server
  template:
    metadata:
      labels:
        app: quiz-backend-server
    spec:
      containers:

      - name: quiz-backend-server
        image: 100xdevs/project-platform-backend-server:e76c9f3c4543d9a17a702b810fc997ce46c4758b
        ports:
        - containerPort: 3001
        env:
        - name: REDIS_HOST
          value: "redis://redis.default.svc.cluster.local:6379"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: PASSWORD
        - name: USER_ID
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: USER_ID
        
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-backend-server
spec:
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
  selector:
    app: quiz-backend-server
