apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-backend-server
  template:
    metadata:
      labels:
        app: quiz-backend-server
    spec:
      containers:

      - name: quiz-backend-server
        image: 100xdevs/project-platform-backend-server:90e8672165e9274bdccf795fa61b1aa7a4033c24
        ports:
        - containerPort: 3001
        env:
        - name: REDIS_HOST
          value: "redis://redis.default.svc.cluster.local:6379"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-backend-server
spec:
  ports:
  - port: 3001
  selector:
    app: quiz-backend-server
