apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
      - name: backend-server
        image: 100xdevs/project-platform-backend-server:latest
        ports:
        - containerPort: 3001
        env:
        - name: REDIS_HOST
          value: "redis.default.svc.cluster.local:6379"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: backend-server
spec:
  ports:
  - port: 3001
  selector:
    app: backend-server
