apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-backend-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-backend-server
  template:
    metadata:
      labels:
        app: quiz-backend-server
    spec:
      containers:

      - name: quiz-backend-server
        image: 100xdevs/project-platform-backend-server:647aa56c4b04b15b41c766d3a84d905769cafe10
        ports:
        - containerPort: 3001
        env:
        - name: REDIS_HOST
          value: "redis://redis.default.svc.cluster.local:6379"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_URL
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: ADMIN_USERNAME
        - name: BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: BACKEND_URL
        - name: FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: FRONTEND_URL
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: GOOGLE_CLIENT_SECRET
        
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-backend-server
spec:
  ports:
  - port: 3001
  selector:
    app: quiz-backend-server
