apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-frontend
  template:
    metadata:
      labels:
        app: quiz-frontend
    spec:
      containers:
      - name: quiz-frontend
        image: 100xdevs/project-platform-frontend:a960847106961ae3887e7736bb6bdfe253eac0db
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: quiz-frontend

