apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-worker
  template:
    metadata:
      labels:
        app: quiz-worker
    spec:
      containers:
      - name: quiz-worker
        image: 100xdevs/project-platform-worker:ed00cf8124a378d1c17dd8d905b7a23133f8bf4f
        env:
        - name: REDIS_HOST
          value: "redis://redis.default.svc.cluster.local:6379"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DATABASE_URL
